// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGUHUwlPuHiZ6gnes6-Rq5HXd5Xv6A4uE',
    appId: '1:295518604573:ios:ec6e4bd37804e4aa36a5f4',
    messagingSenderId: '295518604573',
    projectId: 'fluttertodo-7f794',
    storageBucket: 'fluttertodo-7f794.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsPHkY1JITffapPeKFpGFZBUsIqsL-5ws',
    appId: '1:295518604573:web:0c78519f23b0cdad36a5f4',
    messagingSenderId: '295518604573',
    projectId: 'fluttertodo-7f794',
    authDomain: 'fluttertodo-7f794.firebaseapp.com',
    storageBucket: 'fluttertodo-7f794.firebasestorage.app',
    measurementId: 'G-SKY3WPY91F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUHUwlPuHiZ6gnes6-Rq5HXd5Xv6A4uE',
    appId: '1:295518604573:ios:ec6e4bd37804e4aa36a5f4',
    messagingSenderId: '295518604573',
    projectId: 'fluttertodo-7f794',
    storageBucket: 'fluttertodo-7f794.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaW5uX3MCNN9D0S1YQFIM8SyG0vtF49ZU',
    appId: '1:295518604573:android:da3c4d422d81138b36a5f4',
    messagingSenderId: '295518604573',
    projectId: 'fluttertodo-7f794',
    storageBucket: 'fluttertodo-7f794.firebasestorage.app',
  );

}